# Generated by Django 4.1 on 2022-08-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Renegade', 'Renegade'), ('News', 'News'), ('Magazine', 'Magazine'), ('TRavel-News', 'Travel_News')], default='Web-dev', max_length=160, null=True),
        ),
    ]
